name: Schedule and Run

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
    paths:
      - "**/**/*.sql"
      - "**/**/**/*.sql"
      - "**/*.sql"
      - "*.sql"
  schedule:
    - cron: "15 1-23/2 * * *"
  workflow_dispatch:
concurrency: ${{ github.ref }}

env:
  GCP_SA: chienle-sa@agile-scheme-394814.iam.gserviceaccount.com

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - id: authenticate
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY}}

      - run: |
          pip install dbt-core==1.6.6 dbt-bigquery==1.6.4
          dbt deps
      - name: Schedule flow
        id: schedule_flow
        if: github.event_name == 'schedule'
        run: |
          dbt run --profiles-dir $PWD --project-dir $PWD --exclude config.materialized:view --select config.tags:fact config.tags:incremental
          dbt snapshot --profiles-dir $PWD --project-dir $PWD
      - name: Push flow
        id: push_flow
        if: github.event_name == 'push'
        run: |
          dbt run --profiles-dir $PWD --project-dir $PWD --select state:modified --defer --state prod
      - name: Pull request flow
        id: pull_request_flow
        if: github.event_name == 'pull_request'
        run: |
          dbt run --profiles-dir $PWD --project-dir $PWD --select state:modified --defer --state prod --target dev
          dbt test --profiles-dir $PWD --project-dir $PWD --select state:modified --defer --state prod --target dev

      - name: Generate docs
        id: compile
        if: github.event_name == 'push'
        run: |
          dbt compile && dbt docs generate --no-compile
          find ./target -name \*.json -exec cp -v '{}' './prod' ';'
        continue-on-error: true
      - name: Add Manifest to Repo
        if: github.event_name == 'push'
        uses: EndBug/add-and-commit@v9
        with:
          add: './prod'
          committer_name: Github Actions
          committer_email: actions@github.com
          message: 'Adding manifest from merge run'
      - name: Deploy to Netlify
        if: github.event_name == 'push'
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: './target'
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
        continue-on-error: true